name = "APattern"
uuid = "190b1fc3-f725-4b56-bc75-d9d21258ce5e"
authors = ["bosakRFSpin <bosak@rfspin.com> and contributors"]
version = "1.0.1"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
