name = "APattern"
uuid = "190b1fc3-f725-4b56-bc75-d9d21258ce5e"
authors = ["bosakRFSpin <bosak@rfspin.com> and contributors"]
version = "1.0.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
BenchmarkTools = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
